# Generated by Django 5.1.2 on 2024-10-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination"), name="unique_source_destination"
            ),
        ),
    ]
