# Generated by Django 5.1.2 on 2024-10-13 23:10

import django.core.validators
import station_api.utils
import station_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0003_route_unique_source_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="crew_image",
            field=models.ImageField(
                null=True,
                upload_to=station_api.utils.crew_image_file_path,
                validators=[
                    station_api.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
    ]
