# Generated by Django 5.1.2 on 2024-10-14 08:34

import django.core.validators
import station_api.utils
import station_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0004_crew_crew_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="train_image",
            field=models.ImageField(
                null=True,
                upload_to=station_api.utils.train_image_file_path,
                validators=[
                    station_api.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
    ]
