# Generated by Django 5.1.2 on 2024-10-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0005_alter_train_train_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="trips", to="station_api.crew"
            ),
        ),
    ]
